<?php

class Geometry
{
    private string $name;

    public function __construct($name)
    {
        $this->name = $name;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getArea()
    {
        return 4 * 5;
    }

}

class Circle extends Geometry
{

    private float $radius;

    public function __construct($name, $radius)
    {
        parent::__construct($name);
        $this->radius = $radius;
    }

    public function getArea(): int
    {
        parent::getArea(); // TODO: Change the autogenerated stub

        return pi() * $this->radius * $this->radius;
    }

}

class Triangle extends Geometry
{

    private float $base;
    private float $height;

    public function __construct($name, $base, $height)
    {
        parent::__construct($name);
        $this->base = $base;
        $this->height = $height;
    }

    public function getArea(): int
    {
        parent::getArea(); // TODO: Change the autogenerated stub

        return $this->base * $this->height * 0.5;
    }

}

class Square extends Geometry
{

    private float $length;

    public function __construct($name, $length)
    {
        parent::__construct($name);
        $this->length = $length;
    }

    public function getArea(): int
    {
        parent::getArea(); // TODO: Change the autogenerated stub

        return $this->length * $this->length;
    }

}

class Calculator
{
    private array $areas = [];

    public function add(Geometry $geometry)
    {
        $this->areas[] = $geometry;
    }

    public function sumArea(): int
    {
        $sum = 0;
        foreach ($this->areas as $area) {
            $sum += $area->getArea();
        }
        return $sum;
    }
}

$areaSum = new Calculator();

while (true) {
    echo "--------------------" . PHP_EOL;
    echo "[1] Calculate circle areas." . PHP_EOL;
    echo "[2] Calculate triangle areas." . PHP_EOL;
    echo "[3] Calculate square areas." . PHP_EOL;
    echo "[4] Calculate all areas." . PHP_EOL;
    echo "[Any] To exit." . PHP_EOL;
    echo PHP_EOL;
    $option = readline('Enter you option: ');

    switch ($option) {
        case 1:
            echo "--------------------" . PHP_EOL;
            echo "Create circle." . PHP_EOL;
            $radius = readline("Enter Circle radius: ");
            $circle = new Circle('Circle', $radius);

            echo "{$circle->getName()} {$circle->getArea()}" . PHP_EOL;
            echo PHP_EOL;
            $areaSum->add($circle);

            break;

        case 2:
            echo "--------------------" . PHP_EOL;
            echo "Create triangle." . PHP_EOL;
            $base = readline('Enter triangle base: ');
            $height = readline('Enter triangle height: ');
            $triangle = new Triangle('Triangle', $base, $height);

            echo "{$triangle->getName()} {$triangle->getArea()}" . PHP_EOL;
            echo PHP_EOL;
            $areaSum->add($triangle);

            break;

        case 3:
            echo "--------------------" . PHP_EOL;
            echo "Create square." . PHP_EOL;
            $length = readline('Enter square length: ');
            $square = new Square('Square', $length);

            echo "{$square->getName()} {$square->getArea()}" . PHP_EOL;
            echo PHP_EOL;
            $areaSum->add($square);

            break;

        case 4:
            echo PHP_EOL;
            echo "Total area sum is: {$areaSum->sumArea()}" . PHP_EOL;
            echo PHP_EOL;
            break;

        default:
            exit;

    }
}

